export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const ADD_QUANTITY_OF_PRODUCT = "ADD_QUANTITY_OF_PRODUCT";
export const DECREASE_QUANTITY_OF_PRODUCT = "DECREASE_QUANTITY_OF_PRODUCT";
export const EMPTY_CART = "EMPTY_CART";
